/**
 * @fileoverview gRPC-Web generated client stub for game
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.31.1
// source: game.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.game = require('./game_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.game.GameServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.game.GameServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.game.JoinRequest,
 *   !proto.game.JoinResponse>}
 */
const methodDescriptor_GameService_JoinGame = new grpc.web.MethodDescriptor(
  '/game.GameService/JoinGame',
  grpc.web.MethodType.UNARY,
  proto.game.JoinRequest,
  proto.game.JoinResponse,
  /**
   * @param {!proto.game.JoinRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.game.JoinResponse.deserializeBinary
);


/**
 * @param {!proto.game.JoinRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.game.JoinResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.game.JoinResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.game.GameServiceClient.prototype.joinGame =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/game.GameService/JoinGame',
      request,
      metadata || {},
      methodDescriptor_GameService_JoinGame,
      callback);
};


/**
 * @param {!proto.game.JoinRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.game.JoinResponse>}
 *     Promise that resolves to the response
 */
proto.game.GameServicePromiseClient.prototype.joinGame =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/game.GameService/JoinGame',
      request,
      metadata || {},
      methodDescriptor_GameService_JoinGame);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.game.GameRequest,
 *   !proto.game.QuestionCard>}
 */
const methodDescriptor_GameService_GetNextQuestion = new grpc.web.MethodDescriptor(
  '/game.GameService/GetNextQuestion',
  grpc.web.MethodType.UNARY,
  proto.game.GameRequest,
  proto.game.QuestionCard,
  /**
   * @param {!proto.game.GameRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.game.QuestionCard.deserializeBinary
);


/**
 * @param {!proto.game.GameRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.game.QuestionCard)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.game.QuestionCard>|undefined}
 *     The XHR Node Readable Stream
 */
proto.game.GameServiceClient.prototype.getNextQuestion =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/game.GameService/GetNextQuestion',
      request,
      metadata || {},
      methodDescriptor_GameService_GetNextQuestion,
      callback);
};


/**
 * @param {!proto.game.GameRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.game.QuestionCard>}
 *     Promise that resolves to the response
 */
proto.game.GameServicePromiseClient.prototype.getNextQuestion =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/game.GameService/GetNextQuestion',
      request,
      metadata || {},
      methodDescriptor_GameService_GetNextQuestion);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.game.AnswerRequest,
 *   !proto.game.AnswerResult>}
 */
const methodDescriptor_GameService_SubmitAnswer = new grpc.web.MethodDescriptor(
  '/game.GameService/SubmitAnswer',
  grpc.web.MethodType.UNARY,
  proto.game.AnswerRequest,
  proto.game.AnswerResult,
  /**
   * @param {!proto.game.AnswerRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.game.AnswerResult.deserializeBinary
);


/**
 * @param {!proto.game.AnswerRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.game.AnswerResult)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.game.AnswerResult>|undefined}
 *     The XHR Node Readable Stream
 */
proto.game.GameServiceClient.prototype.submitAnswer =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/game.GameService/SubmitAnswer',
      request,
      metadata || {},
      methodDescriptor_GameService_SubmitAnswer,
      callback);
};


/**
 * @param {!proto.game.AnswerRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.game.AnswerResult>}
 *     Promise that resolves to the response
 */
proto.game.GameServicePromiseClient.prototype.submitAnswer =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/game.GameService/SubmitAnswer',
      request,
      metadata || {},
      methodDescriptor_GameService_SubmitAnswer);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.game.GameId,
 *   !proto.game.Leaderboard>}
 */
const methodDescriptor_GameService_GetLeaderboard = new grpc.web.MethodDescriptor(
  '/game.GameService/GetLeaderboard',
  grpc.web.MethodType.UNARY,
  proto.game.GameId,
  proto.game.Leaderboard,
  /**
   * @param {!proto.game.GameId} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.game.Leaderboard.deserializeBinary
);


/**
 * @param {!proto.game.GameId} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.game.Leaderboard)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.game.Leaderboard>|undefined}
 *     The XHR Node Readable Stream
 */
proto.game.GameServiceClient.prototype.getLeaderboard =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/game.GameService/GetLeaderboard',
      request,
      metadata || {},
      methodDescriptor_GameService_GetLeaderboard,
      callback);
};


/**
 * @param {!proto.game.GameId} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.game.Leaderboard>}
 *     Promise that resolves to the response
 */
proto.game.GameServicePromiseClient.prototype.getLeaderboard =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/game.GameService/GetLeaderboard',
      request,
      metadata || {},
      methodDescriptor_GameService_GetLeaderboard);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.game.GameId,
 *   !proto.game.LeaderboardUpdate>}
 */
const methodDescriptor_GameService_StreamLeaderboard = new grpc.web.MethodDescriptor(
  '/game.GameService/StreamLeaderboard',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.game.GameId,
  proto.game.LeaderboardUpdate,
  /**
   * @param {!proto.game.GameId} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.game.LeaderboardUpdate.deserializeBinary
);


/**
 * @param {!proto.game.GameId} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.game.LeaderboardUpdate>}
 *     The XHR Node Readable Stream
 */
proto.game.GameServiceClient.prototype.streamLeaderboard =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/game.GameService/StreamLeaderboard',
      request,
      metadata || {},
      methodDescriptor_GameService_StreamLeaderboard);
};


/**
 * @param {!proto.game.GameId} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.game.LeaderboardUpdate>}
 *     The XHR Node Readable Stream
 */
proto.game.GameServicePromiseClient.prototype.streamLeaderboard =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/game.GameService/StreamLeaderboard',
      request,
      metadata || {},
      methodDescriptor_GameService_StreamLeaderboard);
};


module.exports = proto.game;

